### ISSUE TITLE
RPM missing font dependency. F32

### ISSUE THREAD

**Issue by jeffclay** [negativo17/blender#4]
Problem: cannot install the best update candidate for package blender-1:2.83.1-1.fc32.x86_64
  - nothing provides blender-fonts = 2:2.82a-3.fc32 needed by blender-2:2.82a-3.fc32.x86_64

**Comment by scaronni** [comment]
Another package that got lost in the migration. Should be fixed now.
I will update Blender in Fedora soon and push also an update here for the CUDA enabled build.
